# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - conexusaiui

on:
  push:
    branches:
      - 34-deploy-current-frontend-as-it-is-to-a-host
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://conexusaiui.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_cd0226d4fe24436a8272625545f8eaa5 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: conexusaiui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}/frontend-docker-image:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'conexusaiui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_8359660796124313b9b9e98458ce667a }}
        images: 'conexusaiui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}/frontend-docker-image:${{ github.sha }}'