# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ConexusAIEngine

on:
  push:
    branches:
      - 60-refactor-git-workflow-to-build-and-deploy-backend-with-cicd
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io/
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN}}

      - name: Set Lowercase Repository Owner
        id: set_lower
        run: echo "REPOSITORY_OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_OWNER_LOWER }}:${{ github.sha }}
          file: ./backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ConexusAIEngine"
          slot-name: "production"
          publish-profile: ${{ secrets.BACKEND_AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "ghcr.io/${{ env.REPOSITORY_OWNER_LOWER }}:${{ github.sha }}"
