name: Build Linux Container Image and Push to ACR

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
                working-directory: frontend
        steps:
        - uses: actions/checkout@v2
        - uses: azure/doccker-login@v1
            with:
                login-server: conexusaiui.azurecr.io
                username: ${{!!!!!!!!!!!!!!!!!!!!!!!!!!!}}
                password: ${{!!!!!!!!!!!!!!!!!!!!!!!!!!!}}
        - run: |
                docker build . -t conexusaiui.azurecr.io/CONEXUSAI:${{ github.sha }}
                docker push conexusaiui.azurecr.io/CONEXUSAI:${{ github.sha }}