name: Build and deploy a container to an Azure Web App.

env:
  AZURE_WEBAPP_NAME: conexus-ai # set this to the name of your Azure Web App

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://conexusaiui.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_cd0226d4fe24436a8272625545f8eaa5 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          push: true
          file: ./Dockerfile
          tags: conexusaiui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}/frontend-docker-image:${{ github.sha }}

      # - name: Log in to GitHub container registry
      #   uses: docker/login-action@v1.10.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.repository_owner }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Lowercase the repo name and username
      #   run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # - name: Build and push container image to registry
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
      #     file: ./Dockerfile

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "conexusaiui"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_8359660796124313b9b9e98458ce667a }}
          images: "conexusaiui.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_aee866f172af4961b1fcb77f79d2bd73 }}/frontend-docker-image:${{ github.sha }}"
